### ISSUE TITLE
Laravel 10 support needed

### ISSUE THREAD

**Issue by gitantonio** [tonysm/laravel-local-time#5]
Hi, this package will support Laravel 10?

Error when I try to install:
![image](https://github.com/tonysm/local-time-laravel/assets/11718902/55fd8f29-2042-46f4-93ac-9fe3c5e2c6de)

**Comment by tonysm** [comment]
Hey 👋🏼 

I'm not using the package anymore, instead I'm handling this pretty much entirely on the frontend using GitHub's [relative-time-element](https://github.com/github/relative-time-element) package, and adding a tiny Blade component, something like:

```blade
{{-- resources/views/components/relative-time.blade.php --}}
@props(['date'])

<relative-time datetime="{{ $date->format(DateTime::ISO8601) }}">
    {{ $date->toFormattedDateString() }}
</relative-time>
```

Which then I can use anywhere like this:

```blade
<x-relative-time :date="$chirp->created_at" />
```

But I do accept a PR to support Laravel 10, by the way.
